### ISSUE TITLE
do not create cookie "nc_staticfilecache"

### ISSUE THREAD

**Issue by MoppieMop** [saschaende/t3helpers#4]
I think this is for an outdated extension and so we don't need this cookie. In times when you have to explain every cookie, it should not be created.

**Comment by saschaende** [comment]
Good hint, thank you, will update this today!

**Comment by saschaende** [comment]
https://github.com/saschaende/t3helpers/commit/fba79213ad84d42dd812e785d888daa81b5de9f5

**Comment by saschaende** [comment]
https://github.com/saschaende/t3helpers/releases/tag/0.9.37
